functionsDirectory = "/Users/Jay/Downloads/donga-door-to-book 2/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headersOrigin = "config"
plugins = []
redirects = []

[build]
edge_functions = "/Users/Jay/Downloads/donga-door-to-book 2/netlify/edge-functions"
publish = "/Users/Jay/Downloads/donga-door-to-book 2"
publishOrigin = "config"
functions = "/Users/Jay/Downloads/donga-door-to-book 2/netlify/functions"

  [build.environment]

  [build.processing]

    [build.processing.css]

    [build.processing.html]

    [build.processing.images]

    [build.processing.js]

  [build.services]

[functions]

  [functions."*"]

[[headers]]
for = "/*"

  [headers.values]
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "strict-origin-when-cross-origin"